Version =20
VersionRequired =20
PublishOption =1
    RecordSelectors = NotDefault
    NavigationButtons = NotDefault
    DividingLines = NotDefault
    AllowDesignChanges = NotDefault
    DefaultView =0
    TabularCharSet =238
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridY =10
    Width =20522
    DatasheetFontHeight =11
    ItemSuffix =44
    Right =25620
    Bottom =12540
    DatasheetGridlinesColor =14806254
        0x28ab233c0e10e540
    End
    DatasheetFontName ="Calibri"
        0x6801000068010000680100006801000000000000201c0000e010000001000000 ,
        0x010000006801000000000000a10700000100000001000000
    End
    AllowDatasheetView =0
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
            BackStyle =0
            TextFontCharSet =238
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            BackStyle =0
            OldBorderStyle =0
            BorderLineStyle =0
            SizeMode =3
            PictureAlignment =2
            Width =1701
            Height =1701
            BorderColor =16777215
            GridlineColor =16777215
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            TextFontCharSet =238
            Width =1701
            Height =283
            FontSize =11
            FontWeight =400
            FontName ="Calibri"
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            UseTheme =1
            Shape =1
            Gradient =12
            BackThemeColorIndex =4
            BackTint =60.0
            BorderLineStyle =0
            BorderColor =16777215
            BorderThemeColorIndex =4
            BorderTint =60.0
            ThemeFontIndex =1
            HoverThemeColorIndex =4
            HoverTint =40.0
            PressedThemeColorIndex =4
            PressedShade =75.0
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
        End
            BorderLineStyle =0
            Width =1701
            Height =1701
            BorderThemeColorIndex =1
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            BorderShade =65.0
            ShowPageHeaderAndPageFooter =1
        End
            SpecialEffect =2
            OldBorderStyle =1
            Width =4536
            Height =2835
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ForeThemeColorIndex =2
            ForeShade =50.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            Height =240
            GridlineColor =12632256
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            BorderWidth =1
            BorderLineStyle =0
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
            Width =283
            Height =283
            ForeColor =-2
            GridlineThemeColorIndex =1
            GridlineShade =65.0
            HoverColor =-2
            HoverThemeColorIndex =2
            HoverTint =20.0
            PressedColor =-2
            PressedThemeColorIndex =2
            PressedTint =60.0
            HoverForeColor =-2
            HoverForeThemeColorIndex =0
            HoverForeTint =75.0
            PressedForeColor =-2
            PressedForeThemeColorIndex =0
            PressedForeTint =75.0
            BackColor =15790320
            BackThemeColorIndex =1
            OldBorderStyle =0
            BorderLineStyle =0
            BorderThemeColorIndex =3
            BorderShade =90.0
            ThemeFontIndex =1
            TextFontCharSet =238
            FontName ="Calibri"
            FontWeight =400
            FontSize =11
            ForeThemeColorIndex =0
            ForeTint =75.0
        End
            Height =680
            BackColor =16382457
            Name ="NagłówekFormularza"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
                    OverlapFlags =85
                    Left =285
                    Top =120
                    Width =2155
                    Height =420
                    ForeColor =16777215
                    Name ="btnSzanseSprzedazy"
                    Caption ="Szanse sprzedaży"
                    OnClick ="[Event Procedure]"
                    GroupTable =1
                    LeftPadding =90
                    TopPadding =90
                    RightPadding =90
                    BottomPadding =90
                    GridlineColor =10921638

                    LayoutCachedLeft =285
                    LayoutCachedTop =120
                    LayoutCachedWidth =2440
                    LayoutCachedHeight =540
                    LayoutGroup =1
                    ForeThemeColorIndex =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =5026082
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderWidth =1
                    BorderColor =5167783
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =5026082
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =5026082
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeThemeColorIndex =1
                    HoverForeTint =100.0
                    PressedForeThemeColorIndex =1
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =6
                    WebImagePaddingTop =6
                    WebImagePaddingRight =5
                    WebImagePaddingBottom =5
                    Overlaps =1
                End
                    OverlapFlags =85
                    Left =2625
                    Top =120
                    Width =2160
                    Height =420
                    TabIndex =1
                    Name ="Polecenie12"
                    Caption ="Zadania"
                    GroupTable =1
                    LeftPadding =90
                    TopPadding =90
                    RightPadding =90
                    BottomPadding =90
                    GridlineColor =10921638

                    LayoutCachedLeft =2625
                    LayoutCachedTop =120
                    LayoutCachedWidth =4785
                    LayoutCachedHeight =540
                    ColumnStart =1
                    ColumnEnd =1
                    LayoutGroup =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =16382457
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderWidth =1
                    BorderColor =5026082
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =16382457
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =16382457
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeColor =0
                    HoverForeTint =100.0
                    PressedForeColor =0
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =6
                    WebImagePaddingTop =6
                    WebImagePaddingRight =5
                    WebImagePaddingBottom =5
                    Overlaps =1
                End
                    OverlapFlags =85
                    Left =4965
                    Top =120
                    Width =2160
                    Height =420
                    TabIndex =2
                    Name ="Polecenie19"
                    Caption ="Kontakty"
                    GroupTable =1
                    LeftPadding =90
                    TopPadding =90
                    RightPadding =90
                    BottomPadding =90
                    GridlineColor =10921638

                    LayoutCachedLeft =4965
                    LayoutCachedTop =120
                    LayoutCachedWidth =7125
                    LayoutCachedHeight =540
                    ColumnStart =2
                    ColumnEnd =2
                    LayoutGroup =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =16382457
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderWidth =1
                    BorderColor =5026082
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =16382457
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =16382457
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeColor =0
                    HoverForeTint =100.0
                    PressedForeColor =0
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =6
                    WebImagePaddingTop =6
                    WebImagePaddingRight =5
                    WebImagePaddingBottom =5
                    Overlaps =1
                End
                    OverlapFlags =85
                    Left =7305
                    Top =120
                    Width =2160
                    Height =420
                    TabIndex =3
                    Name ="Polecenie24"
                    Caption ="Statystyki"
                    GroupTable =1
                    LeftPadding =90
                    TopPadding =90
                    RightPadding =90
                    BottomPadding =90
                    GridlineColor =10921638

                    LayoutCachedLeft =7305
                    LayoutCachedTop =120
                    LayoutCachedWidth =9465
                    LayoutCachedHeight =540
                    ColumnStart =3
                    ColumnEnd =3
                    LayoutGroup =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =16382457
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderWidth =1
                    BorderColor =5026082
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =16382457
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =16382457
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeColor =0
                    HoverForeTint =100.0
                    PressedForeColor =0
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =6
                    WebImagePaddingTop =6
                    WebImagePaddingRight =5
                    WebImagePaddingBottom =5
                    Overlaps =1
                End
                    OverlapFlags =85
                    Left =9645
                    Top =120
                    Width =2160
                    Height =420
                    TabIndex =4
                    Name ="Polecenie30"
                    Caption ="Ustawienia"
                    GroupTable =1
                    LeftPadding =90
                    TopPadding =90
                    RightPadding =90
                    BottomPadding =90
                    GridlineColor =10921638

                    LayoutCachedLeft =9645
                    LayoutCachedTop =120
                    LayoutCachedWidth =11805
                    LayoutCachedHeight =540
                    ColumnStart =4
                    ColumnEnd =4
                    LayoutGroup =1
                    ForeTint =100.0
                    Gradient =0
                    BackColor =16382457
                    BackThemeColorIndex =-1
                    BackTint =100.0
                    BorderWidth =1
                    BorderColor =5026082
                    BorderThemeColorIndex =-1
                    BorderTint =100.0
                    HoverColor =16382457
                    HoverThemeColorIndex =-1
                    HoverTint =100.0
                    PressedColor =16382457
                    PressedThemeColorIndex =-1
                    PressedShade =100.0
                    HoverForeColor =0
                    HoverForeTint =100.0
                    PressedForeColor =0
                    PressedForeTint =100.0
                    GroupTable =1
                    WebImagePaddingLeft =6
                    WebImagePaddingTop =6
                    WebImagePaddingRight =5
                    WebImagePaddingBottom =5
                    Overlaps =1
                End
            End
        End
            CanGrow = NotDefault
            Height =9931
            Name ="szczegoly"
            AlternateBackColor =15921906
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
                    OverlapFlags =223
                    OldBorderStyle =0
                    Top =2
                    Width =16155
                    Height =7080
                    BorderColor =10921638
                    Name ="f_malyLewy"
                    SourceObject ="Form.szanseSprzedazy"
                    GridlineColor =10921638

                    LayoutCachedTop =2
                    LayoutCachedWidth =16155
                    LayoutCachedHeight =7082
                End
                    OverlapFlags =93
                    OldBorderStyle =0
                    Left =16157
                    Width =2910
                    Height =7083
                    TabIndex =1
                    BorderColor =10921638
                    Name ="f_malyPrawy"
                    SourceObject ="Report.osobyKontaktowePodraport"
                    GridlineColor =10921638

                    LayoutCachedLeft =16157
                    LayoutCachedWidth =19067
                    LayoutCachedHeight =7083
                End
                    Visible = NotDefault
                    OverlapFlags =247
                    OldBorderStyle =0
                    Width =19048
                    Height =8571
                    TabIndex =2
                    BorderColor =10921638
                    Name ="f_duzy"
                    SourceObject ="Form.projekt"
                    GridlineColor =10921638

                    LayoutCachedWidth =19048
                    LayoutCachedHeight =8571
                            OverlapFlags =93
                            Width =1320
                            Height =315
                            BorderColor =8355711
                            ForeColor =8355711
                            Name ="Etykieta43"
                            Caption ="Podrzędny42:"
                            GridlineColor =10921638
                            LayoutCachedWidth =1320
                            LayoutCachedHeight =315
                        End
                    End
                End
            End
        End
            Height =0
            Name ="StopkaFormularza"
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
    End
End
CodeBehindForm
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database
Option Explicit

'Używany z Form_projekty->zmienStatus
Public Sub btnSzanseSprzedazy_Click()
   Call ustawMale("szanseSprzedazy", "osobyKontaktowePodraport", , "ID = 0")
End Sub
